# Development-specific Docker Compose configuration
# Mounts local files for live synchronization
# Uses SQLite as configured in the application's development environment

# TODO(Emiliano): move to PostgreSQL to test with Cloud Run
# TODO(ricc): test with CRun

services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql@latest/data:rw
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  web:
    image: docker.io/library/ruby:3.4.5-slim
    ports:
      - "8080:8080"
    volumes:
      # Mount the entire application directory for live file synchronization
      - .:/rails
      # Mount tmp directory to persist temporary files
      - ./tmp:/rails/tmp
      # Mount logs directory to persist logs
      - ./log:/rails/log
      # Mount storage directory for Active Storage
      - ./storage:/rails/storage
      # Mount the SQLite database file to persist data
      - ./db:/rails/db
    environment:
      - RAILS_ENV=development
      # Eliminato vai tra, mi dicono
      #- REDIS_URL=redis://redis:6379/0
      - WEB_CONSOLE=1
      - PORT=8080
      - APP_NAME="Rails 8 Turbo Chat from DockerCompose"
      - DATABASE_URL=postgres://postgres:password@db:5432/rubyllm_chat_app_development
      - GCLOUD_REGION=europe-west1
      # Set environment variables from .env file if available
      - GCS_BUCKET=${GCS_BUCKET:-}
      - GCS_CREDENTIALS_JSON=${GCS_CREDENTIALS_JSON:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - WORKSHOP_ENVIRONMENT='docker_compose'
    working_dir: /rails
    command: >
     sh -c "
        # Install build tools needed for native gems
        apt-get update && apt-get install -y build-essential libyaml-dev libffi-dev &&
        # Install any missing gems
        bundle config set without 'production' &&
        bundle check || bundle install &&
        # Install foreman if not present
        gem install foreman &&
        # Wait for any necessary services to be ready
        sleep 2 &&
        # Create the database if it doesn't exist
        ./bin/rails db:setup 2>/dev/null || true &&
        ./bin/rails assets:precompile 2>/dev/null || true &&
        # Start the application using bin/dev (which uses foreman), with process override to bind to 0.0.0.0
        PORT=8080 foreman start -f Procfile.dev_docker
      "
    stdin_open: true
    tty: true
    # Enable file synchronization for development
    # This ensures changes in the host are reflected in the container
    security_opt:
      - "no-new-privileges:true"
    depends_on:
      - db

volumes:
  db:

networks:
  default:
    driver: bridge
