

list:
    just -l


db-destroy:
    rails db:drop db:create db:migrate

run:
    bin/dev


migrate-gone-wrong:
    # For CreateMessages (basic column types)
    rails generate migration CreateMessages chat:references role:string content:text model_id:string input_tokens:integer output_tokens:integer tool_call:references

    # For CreateToolCalls (basic column types)
    rails generate migration CreateToolCalls message:references tool_call_id:string name:string arguments:jsonb

test-chat-creation:
    echo 'chat = Chat.last ; chat.ask2("testing monkeypatch")' | rails c
# lets just test that Gemini works..
test-gemini:
    echo 'chat = RubyLLM.chat ; chat.ask "Are you an LLM? Who built you? Whats your cutoff time?"' | rails c

