source "https://rubygems.org"



################################
# Riccardo START
################################
#gem "devise", "~> 4.9"

gem 'async'
gem 'ruby_llm', '~> 1.6', '>= 1.6.3'
#gem "dotenv-rails", "~> 3.1"

# Official
gem 'pry', '~> 0.15.0'
# from GH issue - a guy was using this too.
gem 'rainbow'
# MCP
gem "fast-mcp", "~> 1.4"

################################
# /Riccardo END
################################
